language: python
os: linux
dist: bionic
cache: pip

jobs:
  include:
    - python: '3.8'
      env: COVERAGE=--cov
    - python: '3.7'
    - python: '3.6'
    - python: 'pypy3'
    - python: '2.7'
      env: COVERAGE=--cov
    - python: 'pypy'
    - python: 'nightly'
  allow_failures:
    - python: 'nightly'

install:
  - pip install --upgrade -r requirements.txt
  - |
    if [ -n "$COVERAGE" ]; then
      pip install coveralls
    fi
  - pip install -e .

script:
  - pytest --flake8 $COVERAGE

after_success:
  - |
    if [ -n "$COVERAGE" ]; then
      coveralls
    fi
